### ISSUE TITLE
PHP Framework Block

### ISSUE THREAD

**Issue by HenryClark1** [Azure/App-Service-Migration-Tool#5]
#### Investigative information

Please provide the following:

- UTC Timestamp: Thu, 11 Apr 2019 00:57:10
- Migration Tool App version : 0.0.3.19032901
- OS Version: Server 2008R2 SP 1

#### Repro steps

Provide the steps required to reproduce the problem:

1. Open App Service Migration Tool as Admin on Shared IIS Server with PHP installed
2. Select simple HTML site for migration not using PHP
3. Receive Error advising PHP Configuration Detected

#### Expected behavior

Provide a description of the expected behavior.

I would think that if the actual selected site isn't using PHP then it would be valid for migration, seems to be picking up on PHP installed on the server, there is no reference to PHP in the sites web.config

#### Actual behavior

Provide a description of the actual behavior observed.

Receive error that PHP Configuration Detected
{"CheckName":"Frameworks","Result":false,"Status":"Block","Title":"Frameworks","Description":"Checks if the site is using unsupported frameworks.","DisplayMessage":"PHP configuration detected","LearnMoreLink":"https://go.microsoft.com/fwlink/?linkid=2084295"},

#### Known workarounds

Provide a description of any known workarounds.

Uninstall PHP from server? Not viable when running 20 sites on single server

**Comment by NitashaV** [comment]
Thanks for reporting this issue! 
We only support migrating ASP.NET apps in the current version of the migration assistant. I agree that we can and should be more upfront about the supported and unsupported scenarios.  we will fix that.

**Comment by HenryClark1** [comment]
Thanks for responding.

I've found that because PHP was installed on the Shared IIS Server it sets index.php and a PHP handler mapping to all sites regardless of if they utilize PHP or not. After removing those references the site is valid to migrate.

Cheers
